# Generated by Django 5.2.15 on 2026-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target_role',
            field=models.CharField(max_length=100),
        ),
    ]
