# Generated by Django 5.2.15 on 2026-06-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_target_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profileskill',
            name='skill_name',
            field=models.CharField(default='Python', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
